{% set name = "control" %}
{% set version = "0.9.1" %}
{% set sha256 = "8c9084bf386eafcf5d74008f780fae6dec68d243d18a380c866ac10a3549f8d3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - matplotlib-base
    - slycot

test:
  imports:
    - control

about:
  home: http://python-control.sourceforge.net
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/python-control/python-control
  doc_url: http://python-control.readthedocs.org/
  summary: 'Python Control Systems Library'

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
    - bnavigator
