{% set name = "control" %}
{% set version = "0.8.1" %}
{% set sha256 = "d01d6dc14888bdfef6878b3e995a4b2b16bc021447291a9b740a9ab0983d34c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    # NOTE : Once Slycot is available as a Windows conda package, update this.
    - slycot  # [unix]

test:
  imports:
    - control

about:
  home: http://python-control.sourceforge.net
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/python-control/python-control
  doc_url: http://python-control.readthedocs.org/
  summary: 'Python Control Systems Library'

extra:
  recipe-maintainers:
    - moorepants
    - murrayrm
