travis:
  secure:
    BINSTAR_TOKEN: eXVbsR40Bgr8Wtzfz1wGBYRYHcO4DTREACBHBH0wP78MNoaJD19ARGEJDccagi7Jwt6fqgAFTFMwnXEmKRqTK8VonUD4lqzQlh/CEYBghzhcBEn4xqX3lsSdT8e99fzPZPZzprKcgY9LT8E6RHXPYbw3AD5YPHv14a7EuKuQcw02R0yY9ZpkgY/ZRPvSh3qNXGOP9F3CZjbGDGaSALqU855fv7/Pn9UgWKCfRj9Qj9YrdGgaRX0XgyUeEYKssQnc6BpdGE9C9XGnbK/AwZ6Bzbe8NzvMPFLtLfP02cKoN67sHaA8qXuSyV1ZSOu7U0tffNNpGOa03Rhv7VXmAcPx0eo3W6vn1ovob1thExL9/gWRP3GXe3bJQQInFsJdkAPoQQp0OMXTNetaB8e3BuBDYDFuJhRQvUdx682fvPwY+Ls6TyGNioRiinYWY1dM2/3jbcJmZQdXORl43Tl8mzgrCZa09l8fgjwhUixlO4jFoclGkEwgfVHlzeKihQNAsV3ki6sJHaiHkvOcvdbQVP0lLkuIbv69HjLQdARj0vSX1o37MsdvioTU7K3V9eUgAmDkvajWl06gvvCKZy0rMdTl/ynyRJ6hXNrRW5odDTy1YtsU282ol8q9UzV0lrahHMHo9MtB8HKQRH2et68vKVW69Kk5XwkRwmULzCMDXdmDcEM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
